### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by padthaitofuhot** [slowpokefarm/se-block-vaporator#8]
I see on the Steam Workshop you've placed this on GitHub so community members may contribute.  However, there is no license file in the repo, so it's unclear what your personal boundaries for in sharing this code.  Have you chosen a license yet?  

If you're undecided on a license, I like to recommend https://creativecommons.org/licenses/by-sa/4.0/ .  It requires derivative works to credit you and share their derivatives back to the community.

Cheers!

**Comment by slowpokefarm** [comment]
Hello! The one you proposed sounds about right, I will add it to the repo. Thank you!

**Comment by CaseyLoufek** [comment]
Sounds good to me, that's one of my favorite licenses.
